### ISSUE TITLE
Implement Dynmap

### ISSUE THREAD

**Issue by draksterau** [StargateMC/Server#110]
Dynmap integration would be fantastic on the server, however;

- Homeworlds must only be viewable to the owner of that world

**Comment by messra20** [comment]
So dynmap wats up with it i thought you said you werent going to utilize it

**Comment by draksterau** [comment]
Hey, so im planning Tenndril as a new feature which will support Gatelog, Factions and Dynmap integration.

A couple of weeks off but it will blow your mind :)

Factions and players will  be able to own worlds....

**Comment by messra20** [comment]
well if thats the case your gonna have to expand the world claim limit from 250 to over 9000 or just something of that nature

**Comment by draksterau** [comment]
I'm not going to let factions fully claim worlds.

Instead, you'll gain rights to the map information and gate addresses if your faction has the most claims on a world.

It'll update once an hour or something.

Still TBC.

**Comment by draksterau** [comment]
Temporarily cancelling this until I complete https://github.com/stargatemc/Tendril.
