### ISSUE TITLE
Ban Mekanism Teleporters

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#111]
Possibility of Mekenism teleporters being used interdimensionally. Reccomendation Ban. thus making gates a secondary means of transportation. Also mekanism teleporters are undetectable by gatelog.

**Comment by draksterau** [comment]
What's the item ids for this?

Are they used for crafting?

**Comment by messra20** [comment]
ill get back to you on the item id but to my knowledge they are not

**Comment by draksterau** [comment]
Fixed: https://github.com/StargateMC/Server/commit/e4e90cbd91f14fc19049a501b8533ca226a02026
