### ISSUE TITLE
Bannable offense suggestion

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#112]
The placing of stargates or other means of interdimensional travel on worlds without homeworld owners permission. Should be a temporary bannable offense following up with a removal of said device. and a ingame warning against further instances.

**Comment by draksterau** [comment]
Until i can limit permissions on a homeworld basis im going to habe to leave it up to players to defend themselves from this.

My plan is to eventually make the owning faction or player able to build gates amd claim  land and that is it.

**Comment by messra20** [comment]
alright well next to claiming the whole world its gonna be an interesting task

**Comment by draksterau** [comment]
Remember non allies/faction members can't open doors etc.

Contain them to your base.

**Comment by messra20** [comment]
true the doors do the trick but if they are enemies it doesnt do much to stop them

**Comment by draksterau** [comment]
If they are enemies you shouldn't have given them your gate address, or should have an iris.
