### ISSUE TITLE
Midway? is a bit odd.

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#118]
Is there a reason why midway is this enormous ring?,and is missing the third gate to the way of milk.

**Comment by draksterau** [comment]
Please get on today man - I need your help!

**Comment by draksterau** [comment]
I'm home 4 hrs from now

**Comment by draksterau** [comment]
Server is in testing mode. I'll re activate  milky when I'm confident it will hold up

**Comment by draksterau** [comment]
Read the website! Lol

**Comment by messra20** [comment]
i really really wish i could get on but i cant my dad owns the laptop wont let me on so tomarrow i find out if i "get a life" and begin job training and if its a thing ill be able to hopefully be able to get my laptop up and running but what i can do is get on TS3 but i wont be able to MC unless you want to over night me a functional laptop which i greatly doubt

**Comment by draksterau** [comment]
Lol... I can't do that mate.
