### ISSUE TITLE
Iris will not auto-close after being opened by a GDO

### ISSUE THREAD

**Issue by DraksterAU** [StargateMC/Server#126]
If a GDO causes a stargate Iris to open (happens for the person who reprogrammed the destination gate) it does not close when the wormhole disconnects.

This will not affect computer apps opening an iris for a valid GDO.

**Comment by DraksterAU** [comment]
Didn't work!

**Comment by mainesi** [comment]
Need to add an irisstate call to it as it says it's opening the iris even is iris is open

**Comment by DraksterAU** [comment]
@mainesi Do you mean change the output so it states the actual Iris state? (Opening/Open/Closed/Closing?)
