### ISSUE TITLE
Factions Integration

### ISSUE THREAD

**Issue by DraksterAU** [StargateMC/Server#151]
Hi @markehme,

Sorry to bother you, but I was wondering if you could lend me a hand briefly?

I'm trying to create three functions that hook into Factions from a forge mod (to customise my server) to do actions based on the ownership or relation to a chunk or player.

I'm deliberately using text strings instead of objects to avoid incompatibility issues between Bukkit and forge..

Would you be able to help me in making these or reference some code that you might have? I only ask because your already an expert on how factions works.

getFactionNameForChunk(x,z,worldName)
GetFactionNameForPlayerName(name)
GetRelationBetweenFactionNames(faction1Name, Faction2Name)

**Comment by DraksterAU** [comment]
@markehme

**Comment by MarkehMe** [comment]
Happy to help out! 

```getFactionNameForChunk``` will have to work using ```PS``` (PS is a pretty cool utility, it's like a Location object but only stores the information you need and can be used to compare say location vs. chunk, or a chunk vs. block) 

```java
PS psChunk = PS.valueOf(chunk);
Faction factionAtChunk = BoardColl.get().getFactionAt(psChunk);
String factionName = factionAtChunk.getName();
```

```GetFactionNameForPlayerName``` will have to use the MPlayer (or UPlayer if Factions 2.6, or FPlayer if Factions 1.6)

```java
MPlayer mplayer = MPlayer.get(playerName); // I think it takes a player name.. I know for sure it takes UUID and Player
Faction faction = mplayer.getFaction();
String factionName = faction.getName();
```

```GetRelationBetweenFactionNames``` thankfully there is an easy way to do this using BoardColl
```java
Faction faction1 = FactionColl.get().getByName(faction1Name);
Faction faction2 = FactionColl.get().getByName(faction2Name);

Rel relation = FactionColl.get().getByName(faction1).getRelationTo(faction2);
```

Heres a few references that may help you:
Rel - https://github.com/MassiveCraft/Factions/blob/master/src/com/massivecraft/factions/Rel.java
Use methods like ```relation.isAtLeast(Rel.TRUCE);``` for example to speed up tasks. If you're showing this rank, use the inbuilt ```relation. getDescFactionOne()``` to get the appropiate name and ```relation. getColor()``` which shows the realtion colour 

BoardColl - https://github.com/MassiveCraft/Factions/blob/master/src/com/massivecraft/factions/entity/BoardColl.java

FactionCol - https://github.com/MassiveCraft/Factions/blob/master/src/com/massivecraft/factions/entity/FactionColl.java

**Comment by DraksterAU** [comment]
Hi @MarkehMe 
Thanks man!!! You have no idea how much time you saved me............... !!!!

Here are the methods I'm using as far. I'm testing it by printing to console the faction name every time a chunk loads (for now).

https://github.com/StargateMC/SGCraft-Modded/blob/master/src/main/java/mod/gcewing/sg/factions.java

Thank you so much 💃

**Comment by MarkehMe** [comment]
Just some follow up for you :smiley: 

```public Player getBukkitPlayer(String name) {```

You can just use ```Bukkit.getPlayer(name); ``` which is much faster. Everything else looks good. Have fun! :tada:

**Comment by DraksterAU** [comment]
Legend!.... but for some reason trying to import bukkit methods early in the game is melting the server : P
Will give it a go tomorrow.

**Comment by DraksterAU** [comment]
Couldn't have done it without your help @MarkehMe !
