### ISSUE TITLE
Mods/Plugins need to be updated.

### ISSUE THREAD

**Issue by draksterau** [StargateMC/Server#2]
Lots of mods are out of date. Needs an update ASAP.

**Comment by messra20** [comment]
SGCraft to 1.9.1
Bibliocraft to 1.9.2
Buildcraft to 1.6.3?
CoFH Core to 3.0.0B9
CodeChickenCore to 1.0.4.29
ThermalFoundation to 1.0.0RC1
OpenComputers to 1.5.0
Galacticraft to 3.07
ExtendedWorkbench to 1.2.1.1

Mods that  i know need updated thus far

**Comment by draksterau** [comment]
Yep, all updating tonight =)

**Comment by messra20** [comment]
Bibliocraft 1.9.2 failed to download

**Comment by draksterau** [comment]
Fixing that, give me 5mins

**Comment by draksterau** [comment]
Optifine Fixed in 0.2.2 client.

**Comment by messra20** [comment]
game crashed report incoming

**Comment by draksterau** [comment]
Closed. all mods are 100% updated.
