### ISSUE TITLE
Stargate entry crash report

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#21]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2/21/15 7:44 AM
Description: Unexpected error

java.lang.IllegalArgumentException: Could not get provider type for dimension 2, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302)
	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:54)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:865)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302)
	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:54)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:865)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [GCEntityClientPlayerMP['messra20'/25595, l='MpServer', x=127.63, y=77.39, z=259.68], MCH_ViewEntityDummy['MissingName'/228, l='MpServer', x=116.50, y=66.62, z=256.50]]
	Chunk stats: MultiplayerChunkCache: 419, 419
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (116,64,256), Chunk: (at 4,4,0 in 7,16; contains blocks 112,0,256 to 127,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 43223 game time, 43223 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 39 total; [EntityZombie['Zombie'/56961, l='MpServer', x=166.50, y=67.00, z=302.50], EntityEnderman['Enderman'/57858, l='MpServer', x=146.91, y=65.00, z=207.66], EntitySpider['Spider'/56964, l='MpServer', x=171.50, y=67.00, z=297.50], EntityZombie['Zombie'/57734, l='MpServer', x=159.50, y=73.00, z=219.50], EntitySkeleton['Skeleton'/1291, l='MpServer', x=-49.37, y=-24.67, z=3.37], EntitySpider['Spider'/57868, l='MpServer', x=98.28, y=70.00, z=216.75], EntityMinecartChest['entity.MinecartChest.name'/142, l='MpServer', x=149.41, y=17.34, z=192.81], EntityCreeper['Creeper'/57877, l='MpServer', x=172.50, y=68.00, z=291.50], GCEntityClientPlayerMP['messra20'/25595, l='MpServer', x=127.63, y=77.39, z=259.68], GCEntityOtherPlayerMP['Bysokar'/20365, l='MpServer', x=127.47, y=74.88, z=245.72], EntityZombie['Zombie'/58022, l='MpServer', x=76.41, y=77.00, z=233.66], EntityZombie['Zombie'/56488, l='MpServer', x=180.50, y=65.00, z=196.50], EntityCreeper['Creeper'/58152, l='MpServer', x=102.66, y=67.00, z=212.50], EntityPig['Pig'/2608, l='MpServer', x=85.81, y=81.00, z=243.19], EntitySheep['Sheep'/2739, l='MpServer', x=155.81, y=70.00, z=294.25], EntityCreeper['Creeper'/57780, l='MpServer', x=144.50, y=65.00, z=206.50], GCEntityOtherPlayerMP['Bysokar'/20365, l='MpServer', x=131.50, y=74.88, z=243.50], EntityZombie['Zombie'/58044, l='MpServer', x=178.50, y=17.00, z=204.50], EntitySkeleton['Skeleton'/58045, l='MpServer', x=177.50, y=17.00, z=208.50], GCEntityOtherPlayerMP['Bysokar'/20365, l='MpServer', x=131.09, y=74.00, z=246.88], EntityZombie['Zombie'/58176, l='MpServer', x=127.50, y=66.00, z=203.50], GCEntityOtherPlayerMP['Bysokar'/20365, l='MpServer', x=127.72, y=78.22, z=248.50], GCEntityOtherPlayerMP['krazykai1501'/22535, l='MpServer', x=126.51, y=75.83, z=257.79], EntityZombie['Zombie'/58061, l='MpServer', x=146.50, y=67.00, z=199.50], EntityChicken['Chicken'/40912, l='MpServer', x=171.50, y=66.00, z=265.50], EntityChicken['Chicken'/40913, l='MpServer', x=173.50, y=66.00, z=266.50], EntityChicken['Chicken'/40914, l='MpServer', x=171.50, y=66.00, z=266.50], EntityEnderman['Enderman'/58068, l='MpServer', x=147.79, y=73.00, z=221.04], EntityItem['item.item.egg'/58072, l='MpServer', x=173.69, y=66.13, z=266.91], EntityHorse['Horse'/40921, l='MpServer', x=190.84, y=72.00, z=219.66], EntityItem['item.item.feather'/57819, l='MpServer', x=173.25, y=66.13, z=266.25], EntityCreeper['Creeper'/58083, l='MpServer', x=114.50, y=66.00, z=209.50], MCH_ViewEntityDummy['MissingName'/228, l='MpServer', x=116.50, y=66.62, z=256.50], EntityWaypointContainer['unknown'/230, l='MpServer', x=0.00, y=0.00, z=0.00], GCEntityOtherPlayerMP['Bysokar'/20365, l='MpServer', x=127.50, y=76.84, z=258.50], EntitySkeleton['Skeleton'/56554, l='MpServer', x=169.50, y=62.00, z=235.50], EntitySkeleton['Skeleton'/57711, l='MpServer', x=134.50, y=70.00, z=221.50], EntityCreeper['Creeper'/58361, l='MpServer', x=110.50, y=66.00, z=210.50], EntityPig['Pig'/34556, l='MpServer', x=158.13, y=72.00, z=305.28]]
	Retry entities: 0 total; []
	Server brand: cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 702590192 bytes (670 MB) / 1664540672 bytes (1587 MB) up to 2130051072 bytes (2031 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -Xincgc -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_B5 76 mods loaded, 76 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1291} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1291} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	appliedenergistics2-core{rv2-beta-8} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems{1.0.3.74} [Not Enough Items] (nei-1.0.3.74.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenEye{0.6} [OpenEye] (openeye-0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IC2{2.2.680-experimental} [IndustrialCraft 2] (ic2-2.2.680.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ImmibisCore{59.0.7} [Immibis Core] (immibiscore-59.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AdvancedMachines{59.0.2} [Advanced Machines] (advancedmachines-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AdvancedRepulsionSystems{59.0.2} [Advanced Repulsion Systems] (advancedrepulsionsystems-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (advancedsolarpanels-3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	appliedenergistics2{rv2-beta-8} [Applied Energistics 2] (appliedenergistics-2b8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Baubles{1.0.1.10} [Baubles] (baubles-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (cofhcore-3.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Core{6.3.6} [BuildCraft] (bc-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Transport{6.3.6} [BC Transport] (bc-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Silicon{6.3.6} [BC Silicon] (bc-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Builders{6.3.6} [BC Builders] (bc-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Energy{6.3.6} [BC Energy] (bc-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Factory{6.3.6} [BC Factory] (bc-6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiblioCraft{1.9.2} [BiblioCraft] (bibliocraft-1.9.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Botania{r1.5-163} [Botania] (botania-1.5.163.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CompactSolars{4.4.39.315} [Compact Solar Arrays] (compactsolars-4.4.39.315.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ComputerCraft{1.7} [ComputerCraft] (computercraft-1.7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	customnpcs{1.7.10c} [CustomNpcs] (customnpcs-1.7.10c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	desertcraft{1.7.2b} [Pam's DesertCraft] (desertcraft-1.7.10a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	extendedWorkbench{1.2.1.1} [Extended Workbench] (extendedworkbench-1.2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	flansmod{4.9.0} [Flan's Mod] (flansmod-4.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forestry{3.4.0.7} [Forestry for Minecraft] (forestry-3.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (furnituremod-3.4.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftCore{3.0.8} [Galacticraft Core] (galacticraftcore-3.0.8.266.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftMars{3.0.8} [Galacticraft Planets] (galacticraftplanets-3.0.8.266.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (gravisuite-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	HoloInventory{1.8.3.86} [HoloInventory] (holoinventory-1.8.3.86.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	LLadders{0.5.0} [Luppii's Ladders] (lupisladders-0.5.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (mantle-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mcheli{0.9.3} [MC Helicopter] (mcheli) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mediccraft{1.0.1 - 1.7.2} [MedicCraft] (mediccraft-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Railcraft{9.5.0.0} [Railcraft] (railcraft-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mekanism{7.1.1} [Mekanism] (mekanism-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MekanismGenerators{7.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MekanismTools{7.1.1} [MekanismTools] (MekanismTools-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Natura{2.2.0} [Natura] (natura-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons{1.12.4.16} [NEI Addons] (neiaddons-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|Botany{1.12.4.16} [NEI Addons: Botany] (neiaddons-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|Forestry{1.12.4.16} [NEI Addons: Forestry] (neiaddons-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|CraftingTables{1.12.4.16} [NEI Addons: Crafting Tables] (neiaddons-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|ExNihilo{1.12.4.16} [NEI Addons: Ex Nihilo] (neiaddons-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Oceancraft{1.4.1} [Oceancraft] (oceancraft-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenMods{0.6} [OpenMods] (openmodslib-0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenBlocks{1.3} [OpenBlocks] (openblocks-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MrTJPCoreMod{1.0.5.11} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.11-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Core{4.5.12.64} [ProjectRed] (projectredbase-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Transmission{4.5.12.64} [ProjectRed-Transmission] (projectredintegration-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (thermalfoundation-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (thermalexpansion-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	StargateTech2{0.7.7-Alpha} [StargateTech 2] (stargatetech-0.7.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenComputers{1.5.0.6} [OpenComputers] (opencomputers-1.5.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Integration{4.5.12.64} [ProjectRed-Integration] (projectredintegration-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Illumination{4.5.12.64} [ProjectRed-Illumination] (projectredlighting-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Expansion{4.5.12.64} [ProjectRed-Expansion] (projectredmechanical-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Transportation{4.5.12.64} [ProjectRed-Transportation] (projectredmechanical-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Exploration{4.5.12.64} [ProjectRed-Exploration] (projectredworld-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	SGCraft{1.9.1} [Greg's SG Craft] (sgcraft-1.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct] (tinkersconstruct-1.6.0d40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Treecapitator{1.7.10} [Treecapitator] (treecapitator-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Tubestuff{59.0.3} [Tubestuff] (tubestuff-59.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	AE2 Version: beta rv2-beta-8 for Forge 10.13.2.1230
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 9.18.10.3215, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [sgmc.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)

**Comment by draksterau** [comment]
When did this occur?
