### ISSUE TITLE
Shapeless recipe conflicts

### ISSUE THREAD

**Issue by DiamondHammer** [StargateMC/Server#26]
Shapeless recipes affecting crafting of Items from Gravisuite and advanced solar panels. 

Known items,
Advanced nano chestplate - Booster uncraftable 
Booster requires 4225 item id - but 4225:1 is the only things craftable.
Molecular Transformer - MT Core uncraftable , issue with Thick neutron refelector meta tag.
MT core recipe requires 4227 item id - but 4227:1 is the only thing craftable.
After some research its down to changes in IC2 reactor items damage indicator changes, not sure how it can be changed.

**Comment by DraksterAU** [comment]
Fixed, 2dfc4621bff704496d0d911b7d9ea0de56463ba6

**Comment by DiamondHammer** [comment]
The recipes in 2dfc462 are all MPS related, the problems i listed are Gravisuite and advanced solars.

**Comment by DraksterAU** [comment]
lol my bad

**Comment by DraksterAU** [comment]
CustomRecipes mod will fix this @DiamondHammer

**Comment by DraksterAU** [comment]
Closing, as recipes seem to be fixed with GT.
