### ISSUE TITLE
Default Ingame settings

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#29]
Adjust settings to be lower end so gameplay will be improved for lower end computers right off the bat will send my reccomended settings as an addition to comment soon

invertYMouse:false
mouseSensitivity:0.5
fov:-0.008742142
gamma:1.0
saturation:0.0
renderDistance:8
guiScale:0
particles:1
bobView:true
anaglyph3d:false
advancedOpengl:false
maxFps:100
fboEnable:true
difficulty:2
fancyGraphics:true
ao:2
clouds:false
resourcePacks:["sgmc.zip"]
lastServer:stargatemc.com:25567
lang:en_US
chatVisibility:0
chatColors:true
chatLinks:true
chatLinksPrompt:true
chatOpacity:1.0
snooperEnabled:true
fullscreen:false
enableVsync:false
hideServerAddress:false
advancedItemTooltips:false
pauseOnLostFocus:true
showCape:true
touchscreen:false
overrideWidth:0
overrideHeight:0
heldItemTooltips:true
chatHeightFocused:1.0
chatHeightUnfocused:0.44366196
chatScale:1.0
chatWidth:1.0
showInventoryAchievementHint:false
mipmapLevels:2
anisotropicFiltering:16
streamBytesPerPixel:0.5
streamMicVolume:1.0
streamSystemVolume:1.0
streamKbps:0.5412844
streamFps:0.31690142
streamCompression:1
streamSendMetadata:true
streamPreferredServer:
streamChatEnabled:0
streamChatUserFilter:0
streamMicToggleBehavior:0
forceUnicodeFont:false
key_key.attack:-100
key_key.use:-99
key_key.forward:17
key_key.left:30
key_key.back:31
key_key.right:32
key_key.jump:57
key_key.sneak:42
key_key.drop:16
key_key.inventory:18
key_key.chat:20
key_key.playerlist:15
key_key.pickItem:-98
key_key.command:53
key_key.screenshot:60
key_key.togglePerspective:63
key_key.smoothCamera:0
key_key.sprint:29
key_key.streamStartStop:64
key_key.streamPauseUnpause:65
key_key.streamCommercial:0
key_key.streamToggleMic:0
key_key.fullscreen:87
key_key.hotbar.1:2
key_key.hotbar.2:3
key_key.hotbar.3:4
key_key.hotbar.4:5
key_key.hotbar.5:6
key_key.hotbar.6:7
key_key.hotbar.7:8
key_key.hotbar.8:9
key_key.hotbar.9:10
key_Zoom:29
key_ALT Key:56
key_Boost Key:29
key_Mode Switch Key:50
key_Side Inventory Key:46
key_Hub Expand Key:45
key_Quest Log:38
key_key.extendedWorkbench.zoomIn:78
key_key.extendedWorkbench.zoomOut:74
key_Down key:29
key_Inventory key:19
key_Bomb Key:47
key_Gun Key:48
key_Control Switch key:46
key_Reload key:19
key_Teams Menu Key:34
key_Teams Scores Key:35
key_Roll Left Key:44
key_Roll Right Key:45
key_Gear Up / Down Key:38
key_Door Open / Close Key:37
key_Mode Switch Key:50
key_Debug Key:68
key_Reload Models Key:67
key_Gravi Fly Key:33
key_Gravi Display Hud:35
key_HoloInventory:0
key_wecui.keys.toggle:0
key_wecui.keys.clear:0
key_VoxelMods Config:0
key_Baubles Inventory:48
key_key.fart.desc:33
key_[GC] Galaxy Map:50
key_[GC] Open Spaceship Inventory:33
key_[GC] Toggle Sensor Goggles Mode:37
key_Mekanism Mode Switch:50
key_Mekanism Voice:22
key_key.materialCosts:56
key_key.clipboardPaste:210
key_railcraft.keybind.loco.faster:52
key_railcraft.keybind.loco.slower:51
key_railcraft.keybind.loco.mode:50
key_railcraft.keybind.loco.whistle:49
key_key.control:29
key_[SGTech2] Activate rings (Down):208
key_[SGTech2] Activate rings (Up):200
key_key.minimap.voxelmapmenu:49
key_key.minimap.waypointhotkey:48
key_key.minimap.zoom:44
key_key.minimap.togglefullscreen:45
key_key.minimap.togglemobs:0
soundCategory_master:0.5529801
soundCategory_music:1.0
soundCategory_record:1.0
soundCategory_weather:1.0
soundCategory_block:1.0
soundCategory_hostile:1.0
soundCategory_neutral:1.0
soundCategory_player:1.0
soundCategory_ambient:1.0

ofRenderDistanceChunks:8
ofFogType:3
ofFogStart:0.8
ofMipmapType:0
ofLoadFar:true
ofPreloadedChunks:2
ofOcclusionFancy:false
ofSmoothFps:true
ofSmoothWorld:false
ofAoLevel:1.0
ofClouds:1
ofCloudsHeight:1.0
ofTrees:1
ofGrass:0
ofDroppedItems:0
ofRain:3
ofWater:1
ofAnimatedWater:2
ofAnimatedLava:1
ofAnimatedFire:false
ofAnimatedPortal:false
ofAnimatedRedstone:true
ofAnimatedExplosion:false
ofAnimatedFlame:true
ofAnimatedSmoke:false
ofVoidParticles:false
ofWaterParticles:true
ofPortalParticles:true
ofPotionParticles:true
ofDrippingWaterLava:true
ofAnimatedTerrain:false
ofAnimatedTextures:false
ofAnimatedItems:false
ofRainSplash:false
ofLagometer:false
ofAutoSaveTicks:4000
ofBetterGrass:3
ofConnectedTextures:1
ofWeather:true
ofSky:true
ofStars:true
ofSunMoon:true
ofChunkUpdates:1
ofChunkLoading:0
ofChunkUpdatesDynamic:false
ofTime:0
ofClearWater:true
ofDepthFog:false
ofAaLevel:0
ofProfiler:false
ofBetterSnow:false
ofSwampColors:true
ofRandomMobs:false
ofSmoothBiomes:false
ofCustomFonts:true
ofCustomColors:false
ofCustomSky:false
ofShowCapes:false
ofNaturalTextures:true
ofLazyChunkLoading:false
ofFullscreenMode:Default
ofFastMath:true
ofFastRender:true
ofTranslucentBlocks:1

**Comment by draksterau** [comment]
Good idea. Will do

**Comment by draksterau** [comment]
I will be adding in a setting that reduces all graphics to minimal, with the exception of Fog being disabled as it conflicts with the SGC gate room.
