### ISSUE TITLE
Client Crash-Report

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#31]
I tried opening /market listings and i crashed so here is the report

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2/25/15 9:41 AM
Description: Rendering item

java.lang.IllegalStateException: Already tesselating!
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
	at net.minecraft.client.renderer.RenderBlocks.func_147800_a(RenderBlocks.java:9276)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:446)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:488)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1357)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
	at net.minecraft.client.renderer.RenderBlocks.func_147800_a(RenderBlocks.java:9276)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:446)

-- Item being rendered --
Details:
	Item Type: mods.immibis.ars.ItemMachines@2ca3de0f
	Item Aux: 5
	Item NBT: {display:{Lore:[0:"§d§3§4§6",1:"§fPrice: $3678",2:"§fSeller: §7§oJaffa Black Market",3:"§e<click to buy>",4:"§d<infinite>"]},id:1316s,Count:1b,Damage:5s}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:488)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiChest
	Mouse location: Scaled: (267, 139). Absolute: (800, 419)
	Screen size: Scaled: (534, 280). Absolute: (1600, 838). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 3 total; [GCEntityClientPlayerMP['messra20'/37, l='MpServer', x=234.75, y=54.62, z=745.23], MCH_ViewEntityDummy['MissingName'/259, l='MpServer', x=-191.50, y=66.62, z=256.50], MCH_ViewEntityDummy['MissingName'/259, l='MpServer', x=-191.50, y=66.62, z=256.50]]
	Chunk stats: MultiplayerChunkCache: 400, 400
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-192,64,256), Chunk: (at 0,4,0 in -12,16; contains blocks -192,0,256 to -177,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 6720561 game time, 6967176 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 52 total; [IrisEntity['entity.SGCraft.Stargate Iris.name'/126209, l='MpServer', x=234.50, y=59.50, z=742.50], MCH_ViewEntityDummy['MissingName'/259, l='MpServer', x=-191.50, y=66.62, z=256.50], MCH_EntityVehicle['entity.mcheli.MCH.E.Vehicle.name'/126210, l='MpServer', x=234.50, y=71.34, z=737.50], EntityWaypointContainer['unknown'/261, l='MpServer', x=0.00, y=0.00, z=0.00], MCH_EntityVehicle['entity.mcheli.MCH.E.Vehicle.name'/126212, l='MpServer', x=236.50, y=71.34, z=737.50], MCH_EntityVehicle['entity.mcheli.MCH.E.Vehicle.name'/126214, l='MpServer', x=232.50, y=71.34, z=737.50], EntityItemFrame['entity.ItemFrame.name'/126218, l='MpServer', x=233.50, y=66.50, z=753.94], EntityZombie['Zombie'/143895, l='MpServer', x=190.50, y=40.00, z=790.50], EntityItem['item.item.CrabLegs'/142619, l='MpServer', x=279.44, y=71.13, z=800.75], GCEntityClientPlayerMP['messra20'/37, l='MpServer', x=234.75, y=54.62, z=745.23], EntitySkeleton['Skeleton'/143647, l='MpServer', x=188.50, y=12.00, z=800.50], EntityZombie['Zombie'/142114, l='MpServer', x=177.72, y=48.00, z=787.13], EntityCreeper['Creeper'/143650, l='MpServer', x=191.50, y=12.00, z=797.50], EntitySkeleton['Skeleton'/143648, l='MpServer', x=188.50, y=12.00, z=803.50], EntityCreeper['Creeper'/143649, l='MpServer', x=188.50, y=12.00, z=796.50], EntityZombie['Zombie'/143910, l='MpServer', x=192.38, y=13.00, z=796.03], EntityZombie['Zombie'/143911, l='MpServer', x=193.50, y=12.00, z=790.88], EntityCreeper['Creeper'/143914, l='MpServer', x=179.50, y=40.00, z=797.50], EntityItem['item.item.CrabLegs'/140335, l='MpServer', x=219.84, y=60.13, z=810.75], EntitySkeleton['Skeleton'/141641, l='MpServer', x=181.50, y=50.00, z=795.50], EntitySkeleton['Skeleton'/141401, l='MpServer', x=185.16, y=49.00, z=797.41], EntityWitch['Witch'/144473, l='MpServer', x=183.68, y=36.94, z=797.48], EntitySpider['Spider'/804194, l='MpServer', x=-42.28, y=-47.62, z=3.22], EntityZombie['Zombie'/137842, l='MpServer', x=173.06, y=32.82, z=712.48], EntityCrab['Crab'/126327, l='MpServer', x=252.53, y=60.00, z=785.25], EntitySkeleton['Skeleton'/143742, l='MpServer', x=174.50, y=31.00, z=714.50], EntityCreeper['Creeper'/143999, l='MpServer', x=197.16, y=12.00, z=787.90], EntityItem['item.item.bone'/142461, l='MpServer', x=180.97, y=50.13, z=795.09], EntitySkeleton['Skeleton'/143741, l='MpServer', x=173.50, y=31.00, z=713.50], EntityZombie['Zombie'/126337, l='MpServer', x=187.03, y=42.00, z=787.41], EntityZombie['Zombie'/126339, l='MpServer', x=186.69, y=42.00, z=790.69], EntityZombie['Zombie'/126338, l='MpServer', x=187.44, y=41.00, z=789.69], EntityZombie['Zombie'/126340, l='MpServer', x=186.31, y=42.00, z=789.72], EntityCrab['Crab'/126344, l='MpServer', x=279.47, y=71.00, z=800.72], MCH_EntityVehicle['entity.mcheli.MCH.E.Vehicle.name'/126093, l='MpServer', x=234.50, y=71.36, z=715.50], MCH_EntityVehicle['entity.mcheli.MCH.E.Vehicle.name'/126095, l='MpServer', x=232.50, y=71.36, z=715.50], MCH_EntityVehicle['entity.mcheli.MCH.E.Vehicle.name'/126097, l='MpServer', x=236.50, y=71.36, z=715.50], EntityZombie['Zombie'/144538, l='MpServer', x=193.50, y=13.00, z=793.50], EntitySkeleton['Skeleton'/144539, l='MpServer', x=202.50, y=13.00, z=785.50], EntitySpider['Spider'/588951, l='MpServer', x=-38.44, y=-47.62, z=19.13], EntityCreeper['Creeper'/144554, l='MpServer', x=179.50, y=40.00, z=795.50], EntityZombie['Zombie'/142258, l='MpServer', x=181.30, y=32.09, z=801.69], EntityZombie['Zombie'/142000, l='MpServer', x=198.50, y=12.00, z=787.50], EntitySpider['Spider'/567231, l='MpServer', x=-17.18, y=-47.62, z=-29.56], EntityItem['item.item.CrabLegs'/140226, l='MpServer', x=252.63, y=60.13, z=785.41], EntityZombie['Zombie'/142043, l='MpServer', x=183.34, y=34.00, z=789.34], MCH_EntityVehicle['entity.mcheli.MCH.E.Vehicle.name'/126197, l='MpServer', x=231.50, y=71.34, z=735.50], MCH_EntityVehicle['entity.mcheli.MCH.E.Vehicle.name'/126199, l='MpServer', x=231.50, y=71.34, z=733.50], MCH_EntityVehicle['entity.mcheli.MCH.E.Vehicle.name'/126201, l='MpServer', x=231.50, y=71.34, z=731.50], MCH_EntityVehicle['entity.mcheli.MCH.E.Vehicle.name'/126203, l='MpServer', x=237.50, y=71.34, z=735.50], MCH_EntityVehicle['entity.mcheli.MCH.E.Vehicle.name'/126205, l='MpServer', x=237.50, y=71.34, z=733.50], MCH_EntityVehicle['entity.mcheli.MCH.E.Vehicle.name'/126207, l='MpServer', x=237.50, y=71.34, z=731.50]]
	Retry entities: 0 total; []
	Server brand: cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 142717000 bytes (136 MB) / 1335885824 bytes (1274 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_B5 76 mods loaded, 76 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1291} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1291} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	appliedenergistics2-core{rv2-beta-8} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems{1.0.3.74} [Not Enough Items] (nei-1.0.3.74.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenEye{0.6} [OpenEye] (openeye-0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IC2{2.2.680-experimental} [IndustrialCraft 2] (ic2-2.2.680.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ImmibisCore{59.0.7} [Immibis Core] (immibiscore-59.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AdvancedMachines{59.0.2} [Advanced Machines] (advancedmachines-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AdvancedRepulsionSystems{59.0.2} [Advanced Repulsion Systems] (advancedrepulsionsystems-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (advancedsolarpanels-3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	appliedenergistics2{rv2-beta-8} [Applied Energistics 2] (appliedenergistics-2b8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Baubles{1.0.1.10} [Baubles] (baubles-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoFHCore{1.7.10R3.0.0RC1} [CoFH Core] (cofhcore-3.0.0.181.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Core{6.3.7} [BuildCraft] (bc-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Transport{6.3.7} [BC Transport] (bc-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Silicon{6.3.7} [BC Silicon] (bc-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Builders{6.3.7} [BC Builders] (bc-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Energy{6.3.7} [BC Energy] (bc-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Factory{6.3.7} [BC Factory] (bc-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiblioCraft{1.9.2} [BiblioCraft] (bibliocraft-1.9.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Botania{r1.5-163} [Botania] (botania-1.5.163.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CompactSolars{4.4.39.315} [Compact Solar Arrays] (compactsolars-4.4.39.315.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ComputerCraft{1.7} [ComputerCraft] (computercraft-1.7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	customnpcs{1.7.10c} [CustomNpcs] (customnpcs-1.7.10c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	desertcraft{1.7.2b} [Pam's DesertCraft] (desertcraft-1.7.10a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	extendedWorkbench{1.2.1.1} [Extended Workbench] (extendedworkbench-1.2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	flansmod{4.9.0} [Flan's Mod] (flansmod-4.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forestry{3.4.0.7} [Forestry for Minecraft] (forestry-3.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (furnituremod-3.4.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftCore{3.0.8} [Galacticraft Core] (galacticraftcore-3.0.8.266.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftMars{3.0.8} [Galacticraft Planets] (galacticraftplanets-3.0.8.266.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (gravisuite-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	HoloInventory{1.8.3.86} [HoloInventory] (holoinventory-1.8.3.86.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	LLadders{0.5.0} [Luppii's Ladders] (lupisladders-0.5.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (mantle-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mcheli{0.9.3} [MC Helicopter] (mcheli) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mediccraft{1.0.1 - 1.7.2} [MedicCraft] (mediccraft-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Railcraft{9.5.0.0} [Railcraft] (railcraft-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mekanism{7.1.1} [Mekanism] (mekanism-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MekanismGenerators{7.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MekanismTools{7.1.1} [MekanismTools] (MekanismTools-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Natura{2.2.0} [Natura] (natura-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons{1.12.4.16} [NEI Addons] (neiaddons-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|Botany{1.12.4.16} [NEI Addons: Botany] (neiaddons-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|Forestry{1.12.4.16} [NEI Addons: Forestry] (neiaddons-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|CraftingTables{1.12.4.16} [NEI Addons: Crafting Tables] (neiaddons-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|ExNihilo{1.12.4.16} [NEI Addons: Ex Nihilo] (neiaddons-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Oceancraft{1.4.1} [Oceancraft] (oceancraft-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenMods{0.6} [OpenMods] (openmodslib-0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenBlocks{1.3} [OpenBlocks] (openblocks-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MrTJPCoreMod{1.0.5.11} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.11-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Core{4.5.12.64} [ProjectRed] (projectredbase-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Transmission{4.5.12.64} [ProjectRed-Transmission] (projectredintegration-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalFoundation{1.7.10R1.0.0RC2} [Thermal Foundation] (thermalfoundation-1.0.0.53.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalExpansion{1.7.10R4.0.0RC1} [Thermal Expansion] (thermalexpansion-4.0.0.119.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	StargateTech2{0.7.7-Alpha} [StargateTech 2] (stargatetech-0.7.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenComputers{1.5.0.6} [OpenComputers] (opencomputers-1.5.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Integration{4.5.12.64} [ProjectRed-Integration] (projectredintegration-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Illumination{4.5.12.64} [ProjectRed-Illumination] (projectredlighting-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Expansion{4.5.12.64} [ProjectRed-Expansion] (projectredmechanical-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Transportation{4.5.12.64} [ProjectRed-Transportation] (projectredmechanical-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Exploration{4.5.12.64} [ProjectRed-Exploration] (projectredworld-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	SGCraft{1.9.2} [Greg's SG Craft] (sgcraft-1.9.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TConstruct{1.7.10-1.7.1.build803} [Tinkers' Construct] (tinkersconstruct-1.7.1d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Treecapitator{1.7.10} [Treecapitator] (treecapitator-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Tubestuff{59.0.3} [Tubestuff] (tubestuff-59.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	AE2 Version: beta rv2-beta-8 for Forge 10.13.2.1230
	CoFHCore: -[1.7.10]3.0.0RC1-181
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	ThermalFoundation: -[1.7.10]1.0.0RC2-53
	ThermalExpansion: -[1.7.10]4.0.0RC1-119
	TConstruct Environment: Environment healthy.
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 9.18.10.3215, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [sgmc.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by draksterau** [comment]
Closed, fixed as market was corrupt

**Comment by draksterau** [comment]
Appears IMMIBIS mods do not work with Globalmarket.

Has something to do with their names being UUIDs ({012023i319302j123321031203120} not Immibis_core_advanced_machine.
