### ISSUE TITLE
Mob Related Request

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#34]
I once more have been told that the mob spawns zombies and skeletons in particular are just too much for some players so i would suggest knocking it down to easy or trying to limit what the mobs spawn with (this i know you cant do) however i recommend to quell this non sense or at least try to is to install the medieval mobs mod and replace the vanilla mobs with the mod mobs as it is an option in the config for said mod this should possibly solve the issue which the mod is stable to my knowledge and to my use of said mod so please attempt to implement this so we can say we tried to solve the issue at hand

**Comment by draksterau** [comment]
No new mods. Sorry.

Mobs fixed in v1.1.2.
