### ISSUE TITLE
[BuildCraft] [Minor] [Quarries fail to break blocks in any location on server]

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#35]
buildcraft quarries are not functioning will look more into this however

**Comment by draksterau** [comment]
Where is an example? What do you expect them to do? What are they doing?

Some information would be great..

**Comment by messra20** [comment]
well buildcraft quarries are suppose to mine X by X squares into the ground and extract materials however from what i was told by black they werent doing that however im not entirely sure what it wasnt doing he didnt go into detail however its not an issue anymore atm because he lost his quarry so just keep this on a back burner

**Comment by draksterau** [comment]
Back burner it is. Or crash report :P

**Comment by draksterau** [comment]
Lots of changes in v6.3.7 - maybe he is just doing it wrong.

**Comment by messra20** [comment]
well the information i have from further inquiry is the quarry did wat it suppose to it just wasnt breaking the blocks and it was outside of the faction land so thats not it i would reccomend a demonstration by black to show you wats going on

**Comment by draksterau** [comment]
Not breaking blocks ? Odd. I'll have a look next time I'm on. I'll build a quarry on my world.

**Comment by draksterau** [comment]
Fixed in https://github.com/StargateMC/Server/commit/88352d15e5278e39b9a654991a1bec2265d415d4
