### ISSUE TITLE
Public "overworld" count

### ISSUE THREAD

**Issue by Spoonikle** [StargateMC/Server#36]
Add:
5 large "overworld" planets per galaxy

1k x 1k world boarder

**Comment by DraksterAU** [comment]
Have the following generators available;

EpicCaves (x1)
LargeBiomes (x1)
Ocean (x1)
Desert (x1)
Overworld (x3)
Nether (x1)
End (x1)
Iceworld (HothGenerator) (x1)
CityWorld (x1)
IslandCraft (x1)

Recommend we do the above and have 12 worlds per galaxy, or 60 worlds in total (excluding homeworlds).

**Comment by Spoonikle** [comment]
any information on the generators, how they are made and what i could use to seach for more. example : "Bukkit custom world generator" forum posts or the author contact?

**Comment by DraksterAU** [comment]
I'd search for actual plugins via http://dev.bukkit.org/server-plugins/

**Comment by DraksterAU** [comment]
Im happy with the number of generators we have. For mining worlds we're going to use the WorldReset function in future.

**Comment by DraksterAU** [comment]
@Spoonikle This should be fine now, we will create worlds ad-hoc from now on.

With regards to generators, there are thousands out there, simply point them out to me and Ill test them on my private server. If they work, its as simple as adding the plugin!

NOTE: Anything before v1.6 minecraft is not supported, but you'll find a lot of plugins designed for 1.6 to 1.8 work.
