### ISSUE TITLE
unclaimed land restoration

### ISSUE THREAD

**Issue by Spoonikle** [StargateMC/Server#37]
unclaimed land on public worlds should revert to seed on chunk unload event as long as a player entity is not occupying the chunk.

( logged out players should block the restoration of any chunk they occupy to prevent accidental suffocation deaths in the event that restored blocks occupy the players physical space on re-log )

**Comment by DraksterAU** [comment]
@Spoonikle Been chatting to Diamond..

We might end up (as it is easier) making all worlds a "doomed world", with players able to claim on them.

Then, we pick one world per week and wipe and reset it (with a warning/counter) - meaning worlds will be reset every 60 weeks-ish.

What do you think? Its a great alternative to getting a forge mod or bukkit plugin to do the regen, unless you can do it? I can hook either into factions given a working regenerateChunk(chunk, dimension) function.

**Comment by Spoonikle** [comment]
while the packing up and shipping out might be a minor inconvinence in reality - perception will be knee jerk, "dont build anything cool" on pubs... and i dont blame people.

I will find a vaild chunk restore function for forge.

**Comment by Spoonikle** [comment]
i got some regen code that needs some minor changes, I will look at getting it running later tonight.

**Comment by DraksterAU** [comment]
This issue is now being resolved by Mark over at FactionsPlus....
 https://github.com/MarkehMe/FactionsPlus/issues/189

He is a trooper!!
