### ISSUE TITLE
falling through world

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#40]
it happens to everyone ive experienced this but apparently this instance it didnt correct itself so exoshift was world falling and he was -100000 apparently and it didnt correct something you can do maybe it sounds more like mod error than config tho

**Comment by draksterau** [comment]
Not a mod error. I bet Exo either had shit net or is on the other side of the globe.

**Comment by draksterau** [comment]
I'm going to ask Greg to have stargates chunk loader functionality able to be made permanent.

**Comment by draksterau** [comment]
Lagging players, I've asked greg to see if he can help, though.
