### ISSUE TITLE
Marketplace Retool

### ISSUE THREAD

**Issue by Spoonikle** [StargateMC/Server#40]
Marketplace prices need to be balanced within the current earning potential of players, while providing the mid teir and hard to get and odd resources ( like nether wart, coco-beans, passive mobs like cows )

Market place current prices are an over correction, stagnation is resulting from massively over priced goods - enough to allow competition, yet not enough to bring players to the market frequently for deals since they "cant afford anything"

Players cannot afford most objects on the market, requiring an entire days work to translate into a single object - while some other items are massively undervalued, once again draining cash from the economy as players sink all their income into these items and nowhere else. Example: high teir solar and Radioisotope thermoelectric generators

Current market should switch to reasonable prices on commodities, consumables and utility items ( bags, armor, weapons ) A players income could be used as an insurance from death providing a way to buy gear to quickly get back to work by purchasing/requisitioning "mass-produced" goods from the SGC free Jaffa nation and other trading partners.

With a focus away from machines, players will be checking in often to resupply on cheap consumables, while seeing new listings from players.

**Comment by DraksterAU** [comment]
100% Agreed.

**Comment by DraksterAU** [comment]
Ok, so...

Based on the hard limit players earn from jobs as $10,000 per hour (for now), we'll do the following;

Tier 0 Items, these must not exceed $1000 per item. Food will be cheap (Under $100 per piece)?
Tier 1 Items, containing basic machines and items and must be under $10,000 per item.
Tier 2 will be up to $100k per item.
Tier 3 will be up to $1000k per item (widest ranging tier)
Tier 4 will be up to $5000k per item (this will be stargates and the like)
Tier 5 will be above $10000k and be reserved for items that are inobtainable as well as really hard to get, i.e Personal shields and ZPMs.
