### ISSUE TITLE
new comers note

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#41]
due to crashes caused by unidentified reasons namely and most likely ram i think just incase i being a "moderator" server should have access to stargate parts or just naq and have access to the teleport command incase of emergency such as constant world falling or for the players case have a /escape command with no warm up and of it would have a cool down if you think needed  that will teleport them to surface or something to help prevent the loss of items due to world falling and clear lag until they can be solved so just some ideas that have been tossed my way

**Comment by draksterau** [comment]
Falling through worlds is the fault of a user having shit Internet, not a server issue.

If they don't have shit net, they might be too far away (it happens to Aussies sometimes) to play effectively.

Sorry but I'm going to be able to help with that until I yet the U.S. And oceanic servers running and those will take $$.

**Comment by messra20** [comment]
just so i get a rough idea how much would the US server cost to "activate"

**Comment by draksterau** [comment]
$50-60 usd per month.

I may be moving us there anyway, so hold on tight for a week or so.

Eventually I want 3 servers, separated by midway :D

**Comment by draksterau** [comment]
Working with Greg on a possible support for laggy players.

Means stargates would always keep their chunk active, not just when a wormhole is active.

**Comment by messra20** [comment]
hmm well and you mean seperated by midway as in thats a place players could go to "gate" to another server

**Comment by draksterau** [comment]
Yep

**Comment by draksterau** [comment]
Would be pretty cool

**Comment by draksterau** [comment]
Closing as This isn't a bug. It's laggy players.
