### ISSUE TITLE
moderator perms until issue is fixed

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#42]
it would be nice if i had at least tp perms(no cooldown/warmup) because Exoshift has been falling through the world for 2 days now until the chunk issue is solved(which i know your working on) someway or another atm its no fun for him this would be a temporary fix ill happily let the perms go once its solved and the others agree i should have more moderatory abilities for these instances and other issues that may occur

**Comment by messra20** [comment]
so i hear its fixed for the moment

**Comment by draksterau** [comment]
Al good, but Exo could have used /spawn.

**Comment by messra20** [comment]
Isnt there a warm up on that

**Comment by draksterau** [comment]
Good point, I'll look at removing it. But I'll increase the cool down so people don't just use it to avoid dying in pvp
