### ISSUE TITLE
Homeworlds to become Creative Mode

### ISSUE THREAD

**Issue by Spoonikle** [StargateMC/Server#43]
Homeworlds are to become Creative mode, whilst still relying on survival earned money and faction claims for grief prevention.

This will be achieved by;

- On Player Clone, a player will be checked if they are on a homeworld. If they are, they will be set to creative IF their gamemode is not already creative.
- On Player Clone, a player will be checked if they are on a homeworld. If they arent, they will be set to survival IF their gamemode is not already survival.
- Bukkit Plugin will be used to handle switching inventories when a player is made Creative or Survival
- Removing The restriction on players visiting - allowing AutoGDO to actually serve a purpose.

**Comment by DraksterAU** [comment]
This has been taken care of :)
