### ISSUE TITLE
[Veterans Bonus] - Promote to Tollan after 1 week of playing regularly.

### ISSUE THREAD

**Issue by draksterau** [StargateMC/Server#45]
After 1 week of regularly playing, promote users to Tollan automatically.

**Comment by messra20** [comment]
Wat is the advantage here with tolan

**Comment by draksterau** [comment]
At the moment, they do not lose items on death. That's one...

**Comment by messra20** [comment]
i think you need to fix that for ancient as well and because i lost my items on impact with Iris so i think that needs to be changed in config possibly

**Comment by draksterau** [comment]
No. Dying on an iris is your own fault lol.
People need to be afraid to go to a gate they don't know.

Tollan will keep their items tho. Ill fix group inheritance so it will solve your issue.
