### ISSUE TITLE
World fill request

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#46]
Blackfire would like all of his chunks loaded so he can find his"native gates"

**Comment by draksterau** [comment]
not willing to do that as of yet, I'm looking at shrinking the size of personal worlds to 1,000 blocks across to encourage people to use them more as a base - then go to public worlds to mine etc.

**Comment by draksterau** [comment]
If someone built at 1500 away from spawn, I might just adjust spawn to be their base, and do 1000 blocks from there.
