### ISSUE TITLE
Factions chunk Pillaging

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#49]
we attempted to pillage the intruder chunk and it said that they had enough power to keep it and im thinking thats not right we have a ton more power than what the federation has so whats up with that

**Comment by draksterau** [comment]
Not a bug. Reduce their power to less than the number of chunks they hold to make some vulnerable to claims. Nothing to do with your power against theres.

Only way for them to lose power is to die. (-5 power per death, it regenerates at 5 per hour).
