### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#5]
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 2/20/15 5:58 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.thevoxelbox.voxelmenu.VoxelMenuModCore.onTick(VoxelMenuModCore.java:362)
	at com.mumfrey.liteloader.client.ClientEvents.onTick(ClientEvents.java:665)
	at com.mumfrey.liteloader.client.CallbackProxyClient.onTick(CallbackProxyClient.java:146)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 69651088 bytes (66 MB) / 250929152 bytes (239 MB) up to 2130051072 bytes (2031 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -Xincgc -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_B5 111 mods loaded, 111 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded
	FML{7.10.85.1291} [Forge Mod Loader] (modpack.jar) Unloaded
	Forge{10.13.2.1291} [Minecraft Forge] (modpack.jar) Unloaded
	appliedenergistics2-core{rv2-beta-8} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded
	NotEnoughItems{1.0.3.74} [Not Enough Items] (nei-1.0.3.74.jar) Unloaded
	OpenEye{0.6} [OpenEye] (openeye-0.6.jar) Unloaded
	OpenModsCore{@VERSION@} [OpenModsCore] (minecraft.jar) Unloaded
	AdvancedMachines{59.0.2} [Advanced Machines] (advancedmachines-59.0.2.jar) Unloaded
	AdvancedRepulsionSystems{59.0.1} [Advanced Repulsion Systems] (advancedrepulsionsystems-initial.jar) Unloaded
	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (advancedsolarpanels-3.5.1.jar) Unloaded
	appliedenergistics2{rv2-beta-8} [Applied Energistics 2] (appliedenergistics-2b8.jar) Unloaded
	ArmorStatusHUD{1.27} [ArmorStatusHUD] (armorstatushud-1.27.jar) Unloaded
	Baubles{1.0.1.10} [Baubles] (baubles-1.0.1.10.jar) Unloaded
	BuildCraft|Silicon{6.3.6} [BC Silicon] (bc-6.3.6.jar) Unloaded
	BuildCraft|Core{6.3.6} [BuildCraft] (bc-6.3.6.jar) Unloaded
	BuildCraft|Transport{6.3.6} [BC Transport] (bc-6.3.6.jar) Unloaded
	BuildCraft|Builders{6.3.6} [BC Builders] (bc-6.3.6.jar) Unloaded
	BuildCraft|Energy{6.3.6} [BC Energy] (bc-6.3.6.jar) Unloaded
	BuildCraft|Factory{6.3.6} [BC Factory] (bc-6.3.6.jar) Unloaded
	BiblioCraft{1.9.2} [BiblioCraft] (bibliocraft-1.9.2.jar) Unloaded
	Botania{r1.5-163} [Botania] (botania-1.5.163.jar) Unloaded
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (cofhcore-3.0.0.jar) Unloaded
	CompactSolars{4.4.39.315} [Compact Solar Arrays] (compactsolars-4.4.39.315.jar) Unloaded
	customnpcs{1.7.10c} [CustomNpcs] (customnpcs-1.7.10c.zip) Unloaded
	DamageIndicatorsMod{3.2.0} [Damage Indicators] (damageindicators-3.2.0.jar) Unloaded
	desertcraft{1.7.2b} [Pam's DesertCraft] (desertcraft-1.7.10a.jar) Unloaded
	DirectionHUD{1.23} [DirectionHUD] (directionhud-1.23.jar) Unloaded
	extendedWorkbench{1.2.1.1} [Extended Workbench] (extendedworkbench-1.2.1.1.jar) Unloaded
	FishingNets{1.2.1.5} [Fishing Nets] (fishingnets-initial.jar) Unloaded
	flansmod{4.9.0} [Flan's Mod] (flansmod-4.9.0.jar) Unloaded
	weeeflowers{1.7.2b} [Pam's Weee! Flowers] (flowers-initial.jar) Unloaded
	Forestry{3.4.0.7} [Forestry for Minecraft] (forestry-3.4.0.7.jar) Unloaded
	cfm{3.3.5} [§6MrCrayfish's Furniture Mod] (furnituremod-initial.jar) Unloaded
	GalacticraftCore{3.0.8} [Galacticraft Core] (galacticraftcore-3.0.8.266.jar) Unloaded
	GalacticraftMars{3.0.2} [Galacticraft Planets] (galacticraftplanets-initial.jar) Unloaded
	GraviSuite{1.7.10-2.0.1} [Graviation Suite] (gravisuite-initial.jar) Unloaded
	harvestcraft{1.7.2d} [Pam's HarvestCraft] (harvestcraft-initial.jar) Unloaded
	Highlands{2.2.0} [Highlands] (highlands-initial.jar) Unloaded
	HoloInventory{1.8.3.86} [HoloInventory] (holoinventory-initial.jar) Unloaded
	IC2{2.2.635-experimental} [IndustrialCraft 2] (ic2-initial.jar) Unloaded
	ImmibisCore{59.0.7} [Immibis Core] (immibiscore-59.0.7.jar) Unloaded
	DC1{3.4.2.19} [KingCore] (kingcore-initial.jar) Unloaded
	LLadders{0.3.0} [Luppii's Ladders] (lupisladders-initial.jar) Unloaded
	Mantle{1.7.10-0.3.1.jenkins180} [Mantle] (mantle-initial.jar) Unloaded
	mcheli{0.9.3} [MC Helicopter] (mcheli) Unloaded
	mediccraft{1.0.1 - 1.7.2} [MedicCraft] (mediccraft-initial.jar) Unloaded
	Mekanism{7.1.1} [Mekanism] (mekanism-initial.jar) Unloaded
	MekanismGenerators{7.1.1} [MekanismGenerators] (mekanismgenerators-initial.jar) Unloaded
	MekanismTools{7.1.1} [MekanismTools] (mekanismtools-initial.jar) Unloaded
	meteors{2.13.1} [Falling Meteors] (meteors-initial.jar) Unloaded
	MineFactoryReloaded{1.7.10R2.8.0RC6} [MineFactory Reloaded] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC6} [MFR Compat: Applied Energistics] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC6} [MFR Compat: Atum] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC6} [MFR Compat: BackTools] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC6} [MFR Compat: BuildCraft] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC6} [MFR Compat: Chococraft] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC6} [MFR Compat: ExtraBiomes] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC6} [MFR Compat: Forestry] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC6} [MFR Compat: ForgeMicroblock] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC6} [MFR Compat: IC2] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC6} [MFR Compat: Mystcraft] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC6} [MFR Compat ProjectRed] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC6} [MFR Compat: Railcraft] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC6} [MFR Compat: RP2] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC6} [MFR Compat: Sufficient Biomes] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC6} [MFR Compat: Thaumcraft] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC6} [MFR Compat: Thermal Expansion] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC6} [MFR Compat: Tinkers' Construct] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC6} [MFR Compat: TwilightForest] (mfr-2.8.0.jar) Unloaded
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC6} [MFR Compat: Vanilla] (mfr-2.8.0.jar) Unloaded
	Natura{2.2.0} [Natura] (natura-initial.jar) Unloaded
	NEIAddons{1.12.2.9} [NEI Addons] (neiaddons-initial.jar) Unloaded
	NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany] (neiaddons-initial.jar) Unloaded
	NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry] (neiaddons-initial.jar) Unloaded
	NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables] (neiaddons-initial.jar) Unloaded
	NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo] (neiaddons-initial.jar) Unloaded
	Oceancraft{1.4.1} [Oceancraft] (oceancraft-initial.jar) Unloaded
	OpenBlocks{1.3} [OpenBlocks] (openblocks-initial.jar) Unloaded
	OpenComputers{1.3.4.63} [OpenComputers] (opencomputers-initial.jar) Unloaded
	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (opencomputers-initial.jar) Unloaded
	OpenMods{0.6} [OpenMods] (openmodslib-initial.jar) Unloaded
	parachutemod{1.7.10} [Parachute Mod] (parachutemod-initial.jar) Unloaded
	ProjRed|Core{4.4.8.47} [ProjectRed] (projectredbase-initial.jar) Unloaded
	ProjRed|Compatibility{4.4.8.47} [ProjectRed-Compatibility] (projectredcompat-initial.jar) Unloaded
	ProjRed|Integration{4.4.8.47} [ProjectRed-Integration] (projectredintegration-initial.jar) Unloaded
	ProjRed|Transmission{4.4.8.47} [ProjectRed-Transmission] (projectredintegration-initial.jar) Unloaded
	ProjRed|Illumination{4.4.8.47} [ProjectRed-Illumination] (projectredlighting-initial.jar) Unloaded
	ProjRed|Expansion{4.4.8.47} [ProjectRed-Expansion] (projectredmechanical-initial.jar) Unloaded
	ProjRed|Transportation{4.4.8.47} [ProjectRed-Transportation] (projectredmechanical-initial.jar) Unloaded
	ProjRed|Exploration{4.4.8.47} [ProjectRed-Exploration] (projectredworld-initial.jar) Unloaded
	Railcraft{9.2.2.0} [Railcraft] (railcraft-initial.jar) Unloaded
	RopesPlus{1.6.3} [Ropes+] (ropesplus-initial.jar) Unloaded
	SGCraft{1.3.3} [Greg's SG Craft] (sgcraft-initial.jar) Unloaded
	StargateTech2{0.7.7-Alpha} [StargateTech 2] (stargatetech-0.7.7.jar) Unloaded
	StatusEffectHUD{1.26} [StatusEffectHUD] (statuseffecthud-1.26.jar) Unloaded
	ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (thermalexpansion-4.0.0.jar) Unloaded
	ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation] (thermalfoundation-initial.jar) Unloaded
	TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct] (tinkersconstruct-initial.jar) Unloaded
	Treecapitator{1.7.2} [Treecapitator] (treecapitator-initial.jar) Unloaded
	Tubestuff{59.0.1} [Tubestuff] (tubestuff-initial.jar) Unloaded
	UndergroundBiomes{0.6h} [Underground Biomes Constructs] (undergroundbiomesconstructs-initial.jar) Unloaded
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (wrcbe-1.4.1.9.jar) Unloaded
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (wrcbe-1.4.1.9.jar) Unloaded
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (wrcbe-1.4.1.9.jar) Unloaded
	bspkrsCore{6.12} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.12.jar) Unloaded
	ForgeMicroblock{1.1.0.309} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded
	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded
	McMultipart{1.1.0.309} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 9.18.10.3215, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [sgmc.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)

**Comment by draksterau** [comment]
Im reinstalling, if not, remove optifine and it should work.

**Comment by messra20** [comment]
ok

**Comment by draksterau** [comment]
Crash reports are because the latest version of the client has a ton of new mod updates Working on it.

**Comment by messra20** [comment]
well anyway ive removed optifine and it still crashes so something else is causing an issue

**Comment by draksterau** [comment]
Mekanism!!!

Updated 0.2.3.

**Comment by messra20** [comment]
sadface lol so is there an updated variant of it wen i checked i didnt find any definate answer

**Comment by draksterau** [comment]
Maybe we pick the top 25 server mods… and stick to it.. lol.

**Comment by messra20** [comment]
hmm possibry ill try compiling a list for you so are we having issues with mekanisms i can effectively run without much issue 35 or so mods so ill try to narrow it down to  25 but 35 wouldnt be so bad right

**Comment by draksterau** [comment]
It wouldn’t take away from the game really….

IC2
BC
SGCRAFT
CC
OC
MEKANISM
IC2: Addons (they always are stable)
Galacticraft
Flans mod
MCHELI
bibliocraft
forestry
railcraft

Name more ‘essential’ mods.

**Comment by messra20** [comment]
ok well i know luppii's ladders is a favorite amongst the players so 11 or so more mods to name ok ill get right on that

**Comment by draksterau** [comment]
its just an idea to reduce the number.

But if we get 120 stable, i don’t mind.

**Comment by messra20** [comment]
ill definately shoot lower than 50 i know that much we know falling meteors are a no remove due to breakage underground biomes if thats removed itll cause huge world holes

**Comment by messra20** [comment]
just to get started use the list of mods to be updated i sorta went by ones that peaked my interest in that list ill remove a few from it however

**Comment by messra20** [comment]
i made a new issue so we can bounce a few list idea's to and fro without getting lost in issues

**Comment by draksterau** [comment]
Those mods can be removed now.

**Comment by draksterau** [comment]
Reinstall v0.2.3 and try breaking it for me.

**Comment by messra20** [comment]
breaking it lol if only i had a virtual hammer lol anyway alright ill reinstall/update

**Comment by draksterau** [comment]
Fixed in client 0.1.1
