### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DraksterAU** [StargateMC/Server#51]
Lets list down the activities we have to go... i'll start;

**Market**

- Marketplace populated 

**Jobs**

- Finish Jobs - i.e Miner must be able to mine all ores, cant be abused etc
- Add new ones!

**Skills**

- LequendsQuest Races and classes to be defined
- Define skills in classes with their respective limitations / perks e.g. which items certain races / classes can craft use etc. 

**Website**

- Wiki completion, including a Mod/plugins list with english versions of the config file - @DraksterAU
- Web based Galaxy Browser completion (Wiki page for each galaxy + world + ship) - @DraksterAU
- Web based Credits page, thanking all mod authors, including donation links and the like. 

**Tutorials**

- Tutorial Quests, showing players how to use gates, rings, factions, bounties, economy, Banned item info, market and how to find stargate addresses (/stargates and /whereami commands)

**Pegasus**

- Lantean Quests (Against Wraith)

**MilkyWay**

- Tauri Quests (Against Goauld) - @Spoonikle 

**Destiny**

- Destiny Quests (Against ?) - @DraksterAU

**Ori**

- Ori Quests (Against ?)

**Othalla**

- Othalla Quests (Against ?)

**Builds**

- Oneill Class Asgard Vessel

**Spawns**

- Finalise Spawn hub for new race selection mechanic, Descending acsended choosing path.
- NPC's and quest structure for new Spawn hub. 
- Polishing of all Public world stargate spawns - @DiamondHammer 
- Ensuring each galaxy has at least one of each generator world - @DiamondHammer 

**Mechanics**
- Unclaimed Land Regeneration - Handled by FactionsPlus
- Creative Worlds - @DraksterAU

**Cosmetic**
- 32x Texture pack built-into the jar
- 64x Texture pack downloaded and ready to activate

**Comment by DraksterAU** [comment]
@StargateMC/team  Check this out and comment guys.

**Comment by Spoonikle** [comment]
Dibs on milkyway!!!!

**Comment by DiamondHammer** [comment]
added a few new items to todo list , including the new spawn hub etc.
