### ISSUE TITLE
Starter Kit Suggestion

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#59]
1.P90
2.Burst Fire Mod
3. Red Dot Site(Optional)
4. 32 Steak
5. 1 Basic Energy Cube
6. 2 IC2 Generators
7. 16 Blaze Rods
8. Tactical Helmet
9. Tactical Vest
10. x10 P90 Mags
11.Hang Glider(open Blocks)(optional)
12. x32 Basic Universal Cables
13. Energized smelter
14. Crusher
15. Enrichment Chamber
16.Purification Chamber(optional)
17.Precision Sawmill(optional)
18.Metallurgic Infuser(optional)

**Comment by draksterau** [comment]
I've left a fair few items out that either don't exist (you named them incorrectly) or I don't believe should be available to players right off the bat.

Things like the Weapon mods will be cheap from the market that they can buy at the beginning if they wish (hey, they get 25k!) .

https://github.com/StargateMC/Server/commit/7a48bb1fd02b2f5a5b5d3e862b1e2c797f8b54bc
