### ISSUE TITLE
legends quest levels

### ISSUE THREAD

**Issue by Spoonikle** [StargateMC/Server#59]
With the exsistance of the arena and small player base standard exponential power increses as seen in traditional MMO RPG games are not viable.

**Comment by DraksterAU** [comment]
Would you say the best option is exclude the arenas from the RPG system instead of killing the levelling system?

**Comment by Spoonikle** [comment]
killing the leveling system is a bit much.

we just have to be pragmatic about the utility - all mobs in the game are of equal power - there is no level 40 zone.

the number of players are few.

Next there is what Role play is about - not stats but stories.

allowing for race, faction and class specific things greatly adds to the role play and story - minor differences in player strength help them forge different paths through the world.

the buffs to health, evade, speed, damage should be reduced in scope. Insted of a level 60 having 0 chance of beating a level 80 (as per standard mmo rules the level 80 player has nearly 3x the stats) the levels should provide linear buffs that cap at +50% base line for their race.

Unlike a normal MMO minecraft has so much more to offer than scratching that level up itch, and we already know that such itch can be scratched by levels with 0 stats boosts (call of duty)

**Comment by DraksterAU** [comment]
Ok, I'm happy with things being made linear.... how about you have a look at the configs and create a forked pull request, so we can compare/adjust/discuss before committing changes?

**Comment by DraksterAU** [comment]
Ok, I'm happy with things being made linear.... how about you have a look at the configs and create a forked pull request, so we can compare/adjust/discuss before committing changes?

**Comment by DraksterAU** [comment]
Ok, I'm happy with things being made linear.... how about you have a look at the configs and create a forked pull request, so we can compare/adjust/discuss before committing changes?

**Comment by DraksterAU** [comment]
As we're going to have only passive abilities built into combat classes now I don't feel this one is necessary.

Top level (100) players should only be about 10x as strong as a level 1 now.
