### ISSUE TITLE
Server Mods List

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#6]
SGCraft to 1.9.1
Bibliocraft to 1.9.2
Buildcraft to 1.6.3?
CoFH Core to 3.0.0B9
CodeChickenCore to 1.0.4.29
ThermalFoundation to 1.0.0RC1
Thermal Expansion
OpenComputers to 1.5.0
Galacticraft to 3.07
BpskrCore to 6.16
Tinkers Construct to 1.8.2
IC2
Mr.Crayfishes Furniture Mod to 3.4.7
Flans Mods )
Mekanisms(so were having issues with this one yes?)
HarvestCraft
Applied Energistics2
Project Red
Luppii's ladders to v0.5.0
Advanced Machines,Solar Panels,Repulsion Systems
StargateTech2
Forestry
Railcraft
Computercraft

**Comment by messra20** [comment]
our liteloader mods are still in im sure right?

**Comment by draksterau** [comment]
Yeah.

Test the pack as is now though - the instability from before was because I partially updated the pack, not whole lot. Mechanism needed an update to talk to new IC2 etc.

**Comment by messra20** [comment]
lol ok well i see we jumped from 88 to 108 and im like dude so much lol

**Comment by messra20** [comment]
im getting mod rejections from the server

**Comment by draksterau** [comment]
still have teamspeak?

riftd.com is my server now.

**Comment by messra20** [comment]
ya i got it still

**Comment by draksterau** [comment]
ill come on soonish. downloading it.

**Comment by messra20** [comment]
well im on it now so ya
