### ISSUE TITLE
Market Mailbox creates ghost items for players instead of real ones

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#65]
market items when removed from market mail and attempted to stack they disappear from inventory also certain items from the when you try to place them in the world will disappear

**Comment by draksterau** [comment]
I've tested and validated this.

Issue is caused only when uses actual mailbox, not /market mail.

I've temporarily allowed all players to use /market mail and removed the mailboxes at spawn.

**Comment by draksterau** [comment]
Needed to install MarketCompanion.
