### ISSUE TITLE
"Staff" Permissions

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#66]
Moderators:
TP perms
MW goto because its not just player worlds that they could go to maybe there is a creative world for the server builds to be ported from into the other worlds that you dont want players to have access to
TPA for player worlds only they can tp into there own if need be
Temp Ban perms upto 3 days with a pending review done by "Senior" Staff I E you or me whom ever you want to set it too

also creative if they so choose 
active control over night day cycles and weather

if they choose survival they wouldnt be able to access creative or use night day weather cycle controls
NPC controls should be a no (i dont want to mess with them at least)

if im missing anything thing im missing possible perm wise please do add and ill think on it myself

**Comment by draksterau** [comment]
I agree with;

- Weather (survival or creative)
- Day/night ... I don't think so. They could effectively make it day all the time to increase someone's solar power generated.

- Creative in the MOD world (Separate inventories etc). Ill make a custom command like /modworld to go to the mod world.
Stargates will be banned from using a chevron upgrade in the mod world to ensure other players cant go there.

- Temp bans will come in when I install ban manager (we need players first!) - No need for review, but they will have to state a reason.

**Comment by draksterau** [comment]
Dupe, #70
