### ISSUE TITLE
Ship based transportation mechanics

### ISSUE THREAD

**Issue by DraksterAU** [StargateMC/Server#67]
Players will be able to request to board a transport/military vessel in each galaxy from the spawn world.

This will then allow them to select from the following options, ONCE aboard;

- Goto Homeworld (2 minutes, same galaxy)
- Goto Other Spawn World (X minutes, intergalactic) 

X will be a combination of two galaxy timers; similar to how gate power cost is calculated:

i.e to go from MilkyWay to Ori Galaxy you can add the two together, totalling 20 minutes for travel.

MilkyWay: 5 minutes
Pegasus: 5 minutes
Othalla: 8 minutes
Destiny: 15 minutes
Ori: 15 minutes

This is basically;

1. An NPC on the ship that accepts this request.
2. A timer that counts down and then teleports them to the surface of their desired world.
NOTE: In the event of a disconnect/server crash, they simply need to start the timer again.

This is to make things easier for non-gate travel away from spawns, between galaxies and penalises people with long enough to make them want to get enough power to dial themselves.

Plus side... we can issue achievements, rewards and the like for intergalactic travel by ship... as well as turn each ship into a sub-spawn....

Ships will be;

1. Lantean Aurora : Pegasus + Destiny
2. Daedalus class: MilkyWay
3. Ori Mothership : Ori
4. Asgard Beliskner: Othalla

We will justify this with saying that the wormhole drive used in Season 5 of SGA is being used to transport between Ori and Destiny galaxies to remain semi-canon.

**Comment by mainesi** [comment]
I suggest we keep all windows on all ships closed for the use of wormhole drive

**Comment by DraksterAU** [comment]
This is done. no longer going to use wormhole drive, but simply only allow ship transport between galaxies in the local group (Othala/Pegasus/Milkyway)

The Ori and Destiny galaxies have a ship for homeworld transport only.
