### ISSUE TITLE
Complete "Filler" builds on Lacun

### ISSUE THREAD

**Issue by DraksterAU** [StargateMC/Server#69]
Everywhere that has no direct purpose needs to be populated with trees/forests/paths etc.

Nothing special.... just not so empty (i.e the island)

**Comment by DiamondHammer** [comment]
Main land areas better connected , polishing ongoing,  what are the hidden railways ? I messed one up with some WE while polishing the area with fake Sokar and spoon avatars.

**Comment by DraksterAU** [comment]
Lol, they're just supposed to be an Easter egg - one that allows rapid transport around the island.
