### ISSUE TITLE
Complete Professions

### ISSUE THREAD

**Issue by draksterau** [StargateMC/Server#74]
All professions need to be completed.

**Comment by draksterau** [comment]
Miner: Completed! d77145bc33152e5c64f05fbe874265dcc0656c81

**Comment by messra20** [comment]
Just has a heads up the miner profession could use like another lvl of or two of titles and ranks cause krazy blew through 50 lvls legit in 13mins so here is a suggestion +s=adds

After Adept=50
Journeymen Miner +s 50
Professional Miner +s 100
Master would be Miner +s 150

just to lengthen the profession out.yYou could add a new series of quests later on for the miner profession, or you could just tone down the amount of xp you get by 30% or so and side step this for future instances.

**Comment by draksterau** [comment]
Nah not going to lengthen the profession.

I'll make it harder to get 50 by reducing the xp from mining by 90%

**Comment by draksterau** [comment]
Industrial Miner will take over at 100.

I'll unlock 50-100 when we don't have issues like 13 mins to level to 50!!!

**Comment by draksterau** [comment]
Dupe
