### ISSUE TITLE
Blackfire0909 World

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#76]
So anyway with the unfortunate loss of blackfire0909s world which he isnt happy about btw i know you cant exactly back up to a single world but can he regen his world and be given creative to get himself back up to speed since the planet loss along with all of his machines and equipment but if you can just retrieve his world file that would be great he's not exactly playing until the issue is addressed he sorta depressed lol

**Comment by draksterau** [comment]
How about you read the messages I put up before you report bugs.

His worlds disabled and he can re enable it by talking to Loki.

**Comment by draksterau** [comment]
Hi Mate,

1. Please read all change notes to keep up to date on whats going on on the server.
2. His world is not lost, if he spawned in an empty world, get him to /spawn and then go back to his world with the help of Loki (It re-enables his world).
3. Ill fix the issue where players do not get teleported back to spawn if their world is disabled and they log into it.

Let me know how that goes!

**Comment by messra20** [comment]
ok cool ill let him know i didnt realize it my b
