### ISSUE TITLE
mining laser ban 

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#80]
crafting of mining laser needs to be allowed along with possession just need to disable the use of it in world the mining laser is needed to make thermal centrifuge and something else i believe

**Comment by draksterau** [comment]
It's already banned so players can possess but not
Use it?

**Comment by draksterau** [comment]
I believe this is banned as discussed above, reopen this issue after testing it if you still can use the item.

**Comment by messra20** [comment]
i was doing it wrong lol i didnt pay close enough attention lol
