### ISSUE TITLE
Website mail system

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#86]
sending users messages via the website would be neat to have again it would give a bit more activity to the website

**Comment by draksterau** [comment]
You mean like Universe chat on the site?

**Comment by messra20** [comment]
i mean something like inner website emails of sorts

**Comment by draksterau** [comment]
Are messages emails? are messages PM's ? 

Seems like you want the forum back.

**Comment by messra20** [comment]
well forums part you just sorta stuck in there but ya that would like be nice.Yes, those messages would be PMs website, based emails whatever you wanna call them.
