### ISSUE TITLE
Tutorial Structure

### ISSUE THREAD

**Issue by draksterau** [StargateMC/Server#92]
Tutorial:
	1: Welcome/About
		1: Welcome
		2: Where am I?
		3: What is happening?
		4: Bug Reporting / Suggestions
	2: Communications
		1: Chat Channels
		2: Voice Communications
	3: Factions
		1: Creating A Faction
		2: Joining A Faction
		3: Ranks in Factions
		4: Permissions in Factions
		5: Claiming Territory
		6: Money In Factions
		7: Faction Relations
	4: Economy
		1: Checking Balance
		2: Checking Balance Top 5
		3: What uses Economy?
	5: Market
		1: Viewing Market Listings
		2: Creating a Listing on the Market
		3: Selling To the Marketeers
		4: Finding the worth of an item if sold to the marketeers
	6: NPCFactions
		1: Tauri
		2: Tollan
		3: Free Jaffa
		4: Tokra
		5: Asgard
		6: Ancients
		7: Ascended
		8: Goauld
		9: Wraith
		10: Lucian Alliance
		11: Replicators
		12: Galarans
		13: Ori
	7: Bounties
		1: Placing a Bounty
		2: Viewing Bounties
		3: Accepting A Bounty
		4: Claiming a Bounty
		5: Bounty Fees
		6: Bounty Penalties
	8: Rings & Gates
		1: What are ring platforms?
		2: Using a Ring Platform
		3: What is a stargate?
		4: How do I build a stargate?
		5: What powers a stargate?
		6: Using a Stargate
	9: Gatelog
		1: What is Gatelog?
		2: How can I access Gatelog?
	10: Arenas
		1: What are Arenas?
		2: What rewards will I recieve in arenas?		
	11: Homeworlds
		1: Contacting the Asgard for assistance in locating a new homeworld.
		2: What are Homeworlds?
		3: How Do I get to my homeworld?
		4: Can I access other people's homeworlds?
	12: World Types
		1: What are creative worlds?
		2: What are survival worlds?
		3: What kinds of worlds will I find out there?
	13: Jobs
		1: Why are jobs important?
		2: Learning about Jobs
		3: Picking a Job
	14: Gearing Up
		1: Weapons Training (incl. Modifying a weapon)
		2: Cleared for Weapons Use
		3: Obtaining standard issue weaponry
	15: Obtaining Clearance
		1: Speak with General Oneill
		2: Speak with the Stargate Tecnicians to be whitelisted for gate-travel from the SGC gate.
	16: Travel to new Homeworld
		1: Speak with the Asgard for your initial journey to your new home (and be issued with a stargate to build there!)

**Comment by draksterau** [comment]
@messra20 Anything else should be added man?

**Comment by messra20** [comment]
i honestly think you got it covered except were you gonna put landry on the seat instead of Oneill

**Comment by draksterau** [comment]
Landry doesn't have a skin yet. i might rename/reskin that NPC later.
