### ISSUE TITLE
NPC "Catch Phrases" for various events

### ISSUE THREAD

**Issue by draksterau** [StargateMC/Server#96]
Catch Phrases need to thought up for various npcs, both when a player speaks to them and whenever they are sitting there for a little while.

- World event (Random one every 30sec-1min)
- Interact Event (When a player clicks on them and there is no logic to apply)

Just respond to this issue with as many as you can think of.

**Comment by messra20** [comment]
gate technician: Gate Dialing "Around and she goes where she'll stop nobody knows" Player interaction "come to learn how she ticks have you" Idle chatter "Its quiet too quiet" "i wonder what will step through next time" "aint she a beauty " "its a shame shes a rotary and not touch tone" "i wonder whats going on in pegasus" "im glad we havent heard from kumtriya inna while" "im glad we dont have to clean the Iris" "i wonder whats for lunch" (time variable breakfast lunch dinner) "i wonder what gate travel is like" "its amazing that someone thought up the stargate"

**Comment by messra20** [comment]
Atlantis Gate technician: "Dracula would be jealous" "touch tone the latest craze in gate travel" "im glad we installed a good fashion trinium titanium iris" "i wonder whats going on in the milkyway" "i wondet whats on the menu"
