### ISSUE TITLE
In-game commands

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#97]
my access to commands. /list, talking in universe, and any other commands i might have had access to is gone.

**Comment by draksterau** [comment]
Forgot to restart the server after I updated. Sorry, should be good in a minute.

**Comment by messra20** [comment]
well unless its a special restart ill do that next time this instance occurs

**Comment by draksterau** [comment]
Nah not special. Occasionally after a restart Permissions get reset. Need to restart server to kick them back in.
